// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Text = 1,
  EscapedAt = 2,
  OutputExpr = 3,
  OutputExprParen = 4,
  CodeBlock = 5,
  IfBlock = 6,
  Template = 7
