// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {templateTokens} from "./museLabRazor.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQQOPOOOOOP'#Cf'#CfOOOP'#Cd'#CdQQOPOOOOOP-E6b-E6b",
  stateData: "f~OPPOQPORPOSPOTPOUPO~O",
  goto: "fZPPPPPPPP[PbQRORSRTQOR",
  nodeNames: "⚠ Text EscapedAt OutputExpr OutputExprParen CodeBlock IfBlock Template",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [templateTokens],
  topRules: {"Template":[0,7]},
  tokenPrec: 0
})
