export {
  collectRazorCodeRanges,
  collectTemplateExpressionRanges,
  collectTemplateFoldRanges,
  isInsideTemplateExpression,
  isStatementExpression,
  parseRazorTemplate,
  parseTemplateSurface,
  RazorTemplateParseError,
  validateOutputExpression,
  validateRazorTemplate,
  type TemplateExpressionRange,
  type TemplateFoldRange,
  type TemplateSurfaceSegment,
} from "./parseRazorTemplate";
